### ISSUE TITLE
Could you share the circle_landmarks for surface measurements?

### ISSUE THREAD

**Issue by liren2515** [xiaozai/Anthropometric-clothing-measurements-from-3D-body-scans#2]
Hi, thanks for your interesting work. I tried to search the files in [here](https://github.com/xiaozai/Anthropometric-clothing-measurements-from-3D-body-scans/blob/9c0ca0f2a5c1cf73698abd7851c0570d7bd9230e/Code/Measurement/regression_measurement/surface_measurement.m#L51), which are used to measure the circumference, but didn't find them. 

Are those files are included in the repo? If not, do you mind to share it with me?

Many thanks!

**Comment by xiaozai** [comment]
Hi, Yes, I will update it soon.

**Comment by liren2515** [comment]
> Updated, you can find them under Code/Measurement/measurement_landmarks/
> Actually I have not checked the code, if there is any problem, tell me, I will update soon.
> And you can define your own measurement paths, e.g. using some cutting planes, you can check my another paper:
> **Learning Anthropometry from Rendered Humans** (https://arxiv.org/pdf/2101.02515.pdf)
> where I tried to obtain the measurements by cutting the body.

Sure! Thanks for your help!
